export enum ResponseMessage {
    CREATE_LIST_SUCCESS = 'To-do list successfully created',
    CREATE_LIST_FAIL = 'To-do list cannot be created',
    DELETE_LIST_SUCCESS = 'To-do list successfully deleted',
    DELETE_LIST_FAIL = 'To-do list cannot be deleted',
    GET_LIST_SUCCESS = 'To-do list successfully retrieved',
    GET_LIST_FAIL = 'To-do list not found',
    UPDATE_LIST_SUCCESS = 'To-do list successfully updated',
    UPDATE_LIST_FAIL = 'To-do list cannot be updated',
    CREATE_TASK_SUCCESS = 'Task successfully added',
    CREATE_TASK_FAIL = 'Task could not be added',
    DELETE_TASK_SUCCESS = 'Task successfully deleted',
    DELETE_TASK_FAIL = 'Task could not be deleted',
    UPDATE_TASK_SUCCESS = 'Task successfully updated',
    UPDATE_TASK_FAIL = 'Task could not be updated',
    GET_TASK_SUCCESS = 'Task successfully retrieved',
    GET_TASK_FAIL = 'Task not found',
    ERROR = 'Unknown error.',
    INVALID_REQUEST = 'Invalid Request!',
    GET_ITEM_ERROR = 'Item does not exist',
}
